cloud:
  uniqueID: ""
  appID: ""
  ownerUIN: ""
  secretID: ""
  secretKey: ""
  vpcID: ""
  regionShort: cq
  regionLong: ap-chongqing
  apiDomain: tencentcloudapi.com
  subnets:
    - id: "subnet-xx"
      zone: "ap-chongqing-1"
    - id: "subnet-yy"
      zone: "ap-chongqing-1"

eklet:
  waitSandboxRunningTimeout: 24h
  podUsedApiserver: https://172.1.2.3:6443
  replicaCount: 1
  image:
    ref: ccr.ccs.tencentyun.com/tkeimages/eklet-amd64:v2.11.17
    pullPolicy: IfNotPresent
  service:
    type: NodePort
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 200Mi

scheduler:
  replicaCount: 1
  image:
    ref: ccr.ccs.tencentyun.com/tkeimages/hyperkube:v1.20.6-tke.33
    pullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
  resources:
    requests:
      cpu: 100m

eksAdmission:
  replicaCount: 1
  autoScaleEKS: "\"true\""
  image:
    ref: ccr.ccs.tencentyun.com/tkeimages/eks-admission-controller:v0.3.3
    pullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
  resources:
    limits:
      cpu: 500m
      memory: 500M
    requests:
      cpu: 300m
      memory: 300M